<?php

declare(strict_types=1);

namespace App\Services\Gear;

use App\Models\GearList;
use App\Models\GearListItem;

/**
 * Renders a gear list as a Raidbots-ready SimulationCraft string. Includes a
 * character header (class/spec/race/level/region/server) so paste-and-run
 * works without manual profile setup, then the equipment block with
 * id/bonus/enchant/gem fields per slot.
 *
 * Format mirrors what the in-game `/simc` command emits and matches our
 * SimcStringParserService's expected input — round-trip safe.
 */
final class SimcExportService
{
    /** Map our snake_case slot enum back to the SimC token. */
    private const SLOT_TOKENS = [
        'head'      => 'head',
        'neck'      => 'neck',
        'shoulder'  => 'shoulder',
        'back'      => 'back',
        'chest'     => 'chest',
        'wrist'     => 'wrist',
        'hands'     => 'hands',
        'waist'     => 'waist',
        'legs'      => 'legs',
        'feet'      => 'feet',
        'finger_1'  => 'finger1',
        'finger_2'  => 'finger2',
        'trinket_1' => 'trinket1',
        'trinket_2' => 'trinket2',
        'main_hand' => 'main_hand',
        'off_hand'  => 'off_hand',
        'ranged'    => 'ranged',
    ];

    public function export(GearList $list): string
    {
        $list->loadMissing(['character.realm', 'character.serviceRawData', 'specialization', 'items.item']);

        // No leading comment — QE Live's parser uses the first non-blank line
        // as the player name regardless of the `#` marker, which would turn
        // our header into "Generated by blastr.pro …" inside the resulting
        // upgrade report. The class line ("priest=\"Zaavrik\"") must be the
        // first content line for both Raidbots and QE to parse correctly.
        $lines = $this->headerLines($list);
        $lines[] = '';
        $lines = array_merge($lines, $this->equipmentLines($list));

        return implode("\n", $lines) . "\n";
    }

    /** /simc role mapping from our spec.role enum. */
    private function roleToken(?string $role): ?string
    {
        return match (strtolower((string) $role)) {
            'tank'              => 'tank',
            'heal', 'healer'    => 'spell',  // healers sim as spell-DPS in SimC
            'mdps', 'rdps', 'dps' => 'attack',
            default => null,
        };
    }

    /**
     * @return list<string>
     */
    private function headerLines(GearList $list): array
    {
        $character = $list->character;
        $spec      = $list->specialization;
        $raw       = $character?->serviceRawData;
        $profile   = (array) ($raw?->bnet_profile ?? []);

        $classKey  = strtolower(str_replace([' ', "'"], ['', ''], (string) ($character?->playable_class ?? '')));
        $specKey   = strtolower(str_replace(' ', '_', (string) ($spec?->name ?? '')));
        $raceLabel = $profile['race']['name']['en_US']
            ?? (is_array($profile['race']['name'] ?? null) ? array_values($profile['race']['name'])[0] : null)
            ?? $character?->playable_race
            ?? '';
        $raceKey   = strtolower(str_replace([' ', "'"], ['_', ''], (string) $raceLabel));
        $level     = (int) ($profile['level'] ?? $character?->level ?? 0);
        $region    = strtolower((string) ($character?->realm?->region ?? ''));
        // SimC convention: server slugs use underscores ("tarren_mill"), not
        // dashes. The in-game /simc paste matches this; mismatched dashes
        // would make Raidbots fail to look up the character.
        $server    = str_replace('-', '_', (string) ($character?->realm?->slug ?? ''));
        $name      = (string) ($character?->name ?? 'Character');
        $roleToken = $this->roleToken($spec?->role);

        $lines = [];
        if ($classKey !== '') {
            $lines[] = $classKey . '="' . $name . '"';
        }
        if ($level > 0) $lines[] = 'level=' . $level;
        if ($raceKey !== '') $lines[] = 'race=' . $raceKey;
        if ($region !== '') $lines[] = 'region=' . $region;
        if ($server !== '') $lines[] = 'server=' . $server;
        if ($roleToken)     $lines[] = 'role=' . $roleToken;
        if ($specKey !== '') $lines[] = 'spec=' . $specKey;

        return $lines;
    }

    /**
     * @return list<string>
     */
    private function equipmentLines(GearList $list): array
    {
        $bySlot = $list->items->keyBy('slot');
        $lines = [];

        foreach (GearViewService::ALL_SLOTS as $slot) {
            $li = $bySlot->get($slot);
            if (! $li || ! $li->item_id) continue;

            $token = self::SLOT_TOKENS[$slot] ?? $slot;

            // Match /simc layout: comment with item name + ilvl, then the row.
            $name = $li->item?->name ?? "Item #{$li->item_id}";
            $ilvl = (int) ($li->item_level ?? 0);
            $lines[] = '# ' . $name . ($ilvl > 0 ? ' (' . $ilvl . ')' : '');
            $lines[] = $this->itemLine($token, $li);
        }

        return $lines;
    }

    /**
     * /simc itemline omits ilevel — the bonus_id alone is authoritative for
     * Raidbots to derive ilvl + stats. We follow the same convention so the
     * paste matches what Raidbots' parser expects byte-for-byte.
     */
    private function itemLine(string $token, GearListItem $li): string
    {
        $parts = ['id=' . (int) $li->item_id];

        if ($li->enchant_id) {
            $parts[] = 'enchant_id=' . (int) $li->enchant_id;
        }
        $gemIds = is_array($li->gem_ids) ? $li->gem_ids : [];
        if (! empty($gemIds)) {
            $parts[] = 'gem_id=' . implode('/', array_map('intval', $gemIds));
        }
        $bonusIds = is_array($li->bonus_ids) ? $li->bonus_ids : [];
        if (! empty($bonusIds)) {
            $parts[] = 'bonus_id=' . implode('/', array_map('intval', $bonusIds));
        }

        // SimC convention: blank value after `slot=,` then comma-joined kv pairs.
        return $token . '=,' . implode(',', $parts);
    }
}
