import defaultTheme from 'tailwindcss/defaultTheme';
import forms from '@tailwindcss/forms';
import typography from '@tailwindcss/typography';

/** @type {import('tailwindcss').Config} */
export default {
    content: [
        './vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php',
        './storage/framework/views/*.php',
        './resources/views/**/*.blade.php',
        './resources/js/**/*.vue',
    ],

    theme: {
        extend: {
            colors: {
                "on-tertiary-fixed": "#4c4800",
                "surface-tint": "#4fd3f7",
                "surface-container-highest": "#262528",
                "on-primary-container": "#002934",
                "on-secondary-container": "#fff6f2",
                "surface-bright": "#2c2c2f",
                "secondary-dim": "#fa7902",
                "primary-container": "#14b2d5",
                "on-secondary-fixed": "#582600",
                "tertiary": "#fffadf",
                "secondary-fixed": "#ffc5a4",
                "error": "#ff6e84",
                "tertiary-dim": "#ede45a",
                "error-dim": "#d73357",
                "on-surface-variant": "#adaaad",
                "primary": "#4fd3f7",
                "outline": "#767577",
                "secondary": "#fa7902",
                "background": "#0e0e10",
                "on-primary-fixed": "#002f3a",
                "on-background": "#f9f5f8",
                "primary-dim": "#3cc5e9",
                "on-tertiary-container": "#5e5900",
                "tertiary-container": "#f9ef64",
                "on-surface": "#f9f5f8",
                "surface": "#0e0e10",
                "primary-fixed-dim": "#3cc5e9",
                "on-secondary": "#391600",
                "error-container": "#a70138",
                "surface-variant": "#262528",
                "on-error": "#490013",
                "tertiary-fixed-dim": "#ede45a",
                "secondary-fixed-dim": "#ffb283",
                "primary-fixed": "#4fd3f7",
                "surface-container-low": "#131315",
                "tertiary-fixed": "#fcf266",
                "on-primary": "#004554",
                "outline-variant": "#48474a",
                "inverse-primary": "#00687e",
                "on-error-container": "#ffb2b9",
                "surface-container-high": "#1f1f22",
                "on-primary-fixed-variant": "#004e60",
                "inverse-on-surface": "#565557",
                "on-tertiary-fixed-variant": "#6a6500",
                "surface-container": "#19191c",
                "surface-container-lowest": "#000000",
                "inverse-surface": "#fcf8fb",
                "on-tertiary": "#666100",
                "surface-dim": "#0e0e10",
                "secondary-container": "#984700",
                "on-secondary-fixed-variant": "#833c00",
                "death-knight": "#C41F3B",
                "demon-hunter": "#A330C9",
                "druid": "#FF7C0A",
                "evoker": "#33937F",
                "hunter": "#ABD473",
                "mage": "#3FC7EB",
                "monk": "#00FF98",
                "paladin": "#F48CBA",
                "priest": "#FFFFFF",
                "rogue": "#FFF468",
                "shaman": "#0070DD",
                "warlock": "#8788EE",
                "warrior": "#C69B6D",
                "success-neon": "#39FF14"
            },
            fontFamily: {
                sans: ['Figtree', ...defaultTheme.fontFamily.sans],
                "headline": ["Space Grotesk"],
                "body": ["Manrope"],
                "label": ["Manrope"],
                "slogan": ["Orbitron", "sans-serif"]
            },
            borderRadius: {"DEFAULT": "0.125rem", "lg": "0.25rem", "xl": "0.5rem", "full": "0.75rem"},
            typography: (theme) => ({
                tactical: {
                    css: {
                        '--tw-prose-body': theme('colors.gray[300]'),
                        '--tw-prose-headings': theme('colors.amber[500]'),
                        '--tw-prose-links': theme('colors.amber[400]'),
                        '--tw-prose-bold': theme('colors.gray[100]'),
                        '--tw-prose-counters': theme('colors.amber[500]'),
                        '--tw-prose-bullets': theme('colors.amber[500]'),
                        '--tw-prose-hr': theme('colors.gray[700]'),
                        '--tw-prose-quotes': theme('colors.gray[400]'),
                        '--tw-prose-quote-borders': theme('colors.amber[500]'),
                        h1: { textTransform: 'uppercase', letterSpacing: '0.05em' },
                        h2: { textTransform: 'uppercase', letterSpacing: '0.05em' },
                        h3: { textTransform: 'uppercase', letterSpacing: '0.05em' },
                        a: { textDecoration: 'none', '&:hover': { color: theme('colors.amber[300]') } },
                    },
                },
            }),
        },
    },

    plugins: [forms, typography],
};
