<?php

declare(strict_types=1);

namespace App\Services\Wishlist;

use App\Exceptions\WishlistImportException;
use App\Models\SeasonItem;
use Illuminate\Http\Client\ConnectionException;
use Illuminate\Support\Carbon;
use Illuminate\Support\Facades\Http;
use Illuminate\Support\Facades\Log;

/**
 * Fetches a Questionably Epic Live upgrade report and normalises it to the
 * same DTO shape RaidbotsImportService produces, so WishlistService can
 * consume both transparently.
 *
 * Why we need this: Raidbots simulates DPS/Tank throughput; healers use
 * QE Live for HPS-based item scoring. The API endpoint is the same one
 * QE's frontend hits (verified by reverse-engineering main.js):
 *
 *   GET https://questionablyepic.com/api/getUpgradeReport.php?reportID=X
 *
 * QE returns items by global id only — slot/raid/encounter aren't in the
 * payload. We cross-reference each id against the season_items catalogue
 * so the resulting wishlist rows carry the same metadata as Raidbots imports.
 */
class QELiveImportService
{
    private const URL_PATTERN = '#questionablyepic\.com/(?:live/)?upgradereport/([a-zA-Z0-9_-]+)#';
    private const REPORT_API  = 'https://questionablyepic.com/api/getUpgradeReport.php?reportID=%s';

    /**
     * Map QE's numeric raid difficulty → our string enum. M+ dungeon items
     * (dropDifficulty=6) and Catalyst items have no native QE difficulty;
     * they bucket under 'mythic' so they show under the same tab as Mythic
     * raid items (the user filter would otherwise hide them by default).
     */
    private const RAID_DIFFICULTY_MAP = [
        4 => 'normal',
        5 => 'heroic',
        7 => 'mythic',
        8 => 'raid_finder',
    ];

    /** Multi-word class names that need special class/spec splitting. */
    private const MULTI_WORD_CLASSES = ['Death Knight', 'Demon Hunter'];

    public function isOwnUrl(string $url): bool
    {
        $host = parse_url($url, PHP_URL_HOST);
        return $host !== null && str_contains($host, 'questionablyepic.com');
    }

    public function importFromUrl(string $url): array
    {
        $reportId = $this->extractReportId($url);
        $payload  = $this->fetchPayload($reportId);

        return $this->parsePayload($payload, $url, $reportId);
    }

    private function extractReportId(string $url): string
    {
        if (! preg_match(self::URL_PATTERN, $url, $m)) {
            throw WishlistImportException::invalidPayload("URL has no recognizable QE Live report ID: {$url}");
        }
        return $m[1];
    }

    private function fetchPayload(string $reportId): array
    {
        $endpoint = sprintf(self::REPORT_API, urlencode($reportId));

        try {
            $response = Http::withHeaders([
                'User-Agent' => 'BlastrBot/0.1 (+https://blastr.pro)',
                'Accept'     => 'application/json',
            ])->timeout(30)->get($endpoint);
        } catch (ConnectionException) {
            throw WishlistImportException::fetchFailed($endpoint, 0);
        }

        if (! $response->ok()) {
            throw WishlistImportException::fetchFailed($endpoint, $response->status());
        }

        // QE Live wraps the JSON inside a JSON-encoded string for legacy
        // PHP-side reasons; a successful response is therefore a string we
        // need to decode once more.
        $raw = $response->json();
        if (is_string($raw)) {
            $raw = json_decode($raw, true);
        }
        if (! is_array($raw)) {
            throw WishlistImportException::invalidPayload('QE response body is not JSON');
        }

        if (isset($raw['status']) && $raw['status'] === 'Report not found') {
            throw WishlistImportException::invalidPayload("QE report not found: {$reportId}");
        }

        return $raw;
    }

    /**
     * @return array<string, mixed>
     */
    private function parsePayload(array $payload, string $url, string $reportId): array
    {
        $playerName = (string) ($payload['playername'] ?? '');
        $realm      = (string) ($payload['realm'] ?? '');
        $region     = strtolower((string) ($payload['region'] ?? ''));
        $specRaw    = (string) ($payload['spec'] ?? '');
        $results    = $payload['results'] ?? [];

        if ($playerName === '' || $realm === '' || $specRaw === '') {
            throw WishlistImportException::invalidPayload('QE payload missing player/realm/spec');
        }

        // Older reports created from a SimC paste with a leading `#` comment
        // line had QE pick that comment up as the player name. Detect the
        // legacy "Generated by …" prefix (and any leading `#`) so the import
        // still works against historical reports without forcing a re-run.
        if (str_starts_with($playerName, '#') || str_contains($playerName, 'Generated by')) {
            if (preg_match('/[—\/]\s*([A-Za-z\x{00C0}-\x{017F}]+)\s*\//u', $playerName, $m)) {
                $playerName = $m[1];
            } else {
                throw WishlistImportException::invalidPayload(
                    'QE report has an invalid player name. Re-run the report on questionablyepic.com/live with a fresh /simc paste.'
                );
            }
        }
        if (! is_array($results) || empty($results)) {
            throw WishlistImportException::invalidPayload('QE payload has no results');
        }

        [$className, $specName] = $this->splitClassSpec($specRaw);

        // Normalise to the slugs RaidbotsImportService emits so resolveSpec()
        // in WishlistService doesn't need a second branch.
        $classSlug = strtolower(str_replace(' ', '', $className));
        $specSlug  = strtolower(str_replace(' ', '', $specName));

        $generatedAt = isset($payload['dateCreated'])
            ? $this->parseQeDate((string) $payload['dateCreated'], (string) ($payload['timeCreated'] ?? ''))
            : Carbon::now();

        $simulations = $this->groupResultsByBucket($results);

        return [
            'character' => [
                'name'       => $playerName,
                'realm'      => $realm,
                'region'     => $region !== '' ? $region : null,
                'class_slug' => $classSlug,
                'spec_slug'  => $specSlug,
            ],
            'baseline_dps'     => 0.0, // QE doesn't expose it; not used by storage layer
            'generated_at'     => $generatedAt,
            'source_report_id' => $reportId,
            'source_url'       => $url,
            'public_title'     => $specRaw . ' Upgrade Report',
            'raw_payload'      => $payload,
            'simulations'      => $simulations,
        ];
    }

    /**
     * "Holy Priest" → ["Priest", "Holy"], "Blood Death Knight" → ["Death Knight", "Blood"].
     *
     * @return array{0:string, 1:string}
     */
    private function splitClassSpec(string $combined): array
    {
        foreach (self::MULTI_WORD_CLASSES as $cls) {
            if (str_ends_with($combined, ' ' . $cls)) {
                $spec = trim(substr($combined, 0, -strlen($cls) - 1));
                return [$cls, $spec];
            }
        }
        $pos = strrpos($combined, ' ');
        if ($pos === false) {
            throw WishlistImportException::invalidPayload("Cannot split QE spec '{$combined}' into class+spec");
        }
        return [substr($combined, $pos + 1), substr($combined, 0, $pos)];
    }

    /**
     * Bucket items by (raid_slug, difficulty). raid_slug is resolved per-item
     * by joining season_items (QE doesn't expose instance ids in its payload).
     * Items not in the season catalogue (Crafted/Delves/legacy) are skipped.
     *
     * @return array<int, array{raid_slug:string, difficulty:string, items:array}>
     */
    private function groupResultsByBucket(array $results): array
    {
        $itemIds = array_values(array_unique(array_map(
            fn ($r) => (int) ($r['item'] ?? 0),
            array_filter($results, fn ($r) => isset($r['item']))
        )));
        if (empty($itemIds)) {
            throw WishlistImportException::invalidPayload('QE results had no item ids');
        }

        // One query → keyed catalogue; missing items get skipped at row time.
        $catalog = SeasonItem::query()
            ->whereIn('id', $itemIds)
            ->get(['id', 'inventory_type', 'source_type', 'source_slug', 'encounter_id'])
            ->keyBy('id');

        $buckets = [];
        $skipped = 0;

        foreach ($results as $row) {
            $itemId = (int) ($row['item'] ?? 0);
            $entry  = $catalog->get($itemId);
            if (! $entry) { $skipped++; continue; }

            // Wishlist UI is intentionally raid-only — Mythic+, Catalyst,
            // Crafted, and Delve items don't earn a slot in the per-boss
            // upgrade table. Filter at import time so they never reach the DB.
            if ($entry->source_type !== 'raid') {
                $skipped++;
                continue;
            }

            $dropLoc = (string) ($row['dropLoc'] ?? '');
            $difficulty = $this->difficultyFor($dropLoc, (int) ($row['dropDifficulty'] ?? 0));
            if ($difficulty === null) { $skipped++; continue; }

            $bucketKey = "{$entry->source_slug}|{$difficulty}";
            $buckets[$bucketKey] ??= [
                'raid_slug'  => (string) $entry->source_slug,
                'difficulty' => $difficulty,
                'items'      => [],
            ];

            $rawDiff = (float) ($row['rawDiff'] ?? 0);
            $percent = (float) ($row['percDiff'] ?? 0);
            $value   = (int) round($rawDiff);

            $buckets[$bucketKey]['items'][] = [
                'item_id'      => $itemId,
                'slot'         => $this->normaliseSlot((string) $entry->inventory_type),
                'item_level'   => (int) ($row['level'] ?? 0) ?: null,
                'enchant_id'   => 0, // QE doesn't model enchants per item
                'encounter_id' => (int) ($entry->encounter_id ?? 0),
                'value'        => $value,
                'percent'      => round($percent, 3),
            ];
        }

        if (empty($buckets)) {
            Log::warning('QE Live payload had results but none mapped to season_items', ['skipped' => $skipped]);
            throw WishlistImportException::invalidPayload('QE results had no items matching the season catalogue');
        }

        return array_values($buckets);
    }

    /**
     * "Hands" → "hands", "One-Hand" → "main_hand", paired slots collapse to
     * the singular (finger_1 → finger) — same convention RaidbotsImportService
     * uses so wishlist_items.slot is consistent across sources.
     */
    private function normaliseSlot(string $inventoryType): string
    {
        return match ($inventoryType) {
            'Head'      => 'head',
            'Neck'      => 'neck',
            'Shoulder'  => 'shoulder',
            'Back'      => 'back',
            'Chest'     => 'chest',
            'Wrist'     => 'wrist',
            'Hands'     => 'hands',
            'Waist'     => 'waist',
            'Legs'      => 'legs',
            'Feet'      => 'feet',
            'Finger'    => 'finger',
            'Trinket'   => 'trinket',
            'Off Hand', 'Shield' => 'off_hand',
            'Two-Hand'  => 'two_hand',
            'One-Hand', 'Main Hand' => 'main_hand',
            'Ranged'    => 'ranged',
            default     => strtolower(str_replace([' ', '-'], '_', $inventoryType)),
        };
    }

    private function difficultyFor(string $dropLoc, int $dropDifficulty): ?string
    {
        if ($dropLoc === 'Raid') {
            return self::RAID_DIFFICULTY_MAP[$dropDifficulty] ?? null;
        }
        // Dungeon (M+) + Catalyst items don't have a meaningful raid-difficulty
        // label. Bucket them as 'mythic' so they appear under the default tab.
        return 'mythic';
    }

    private function parseQeDate(string $date, string $time): Carbon
    {
        try {
            return Carbon::parse(trim($date . ' ' . $time));
        } catch (\Throwable) {
            return Carbon::now();
        }
    }
}
