apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "blastr.fullname" . }}-web
  labels:
    {{- include "blastr.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  minAvailable: {{ .Values.web.pdb.minAvailable }}
  selector:
    matchLabels:
      {{- include "blastr.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: web
