apiVersion: v1
kind: Service
metadata:
  name: {{ include "blastr.fullname" . }}-web
  labels:
    {{- include "blastr.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  type: ClusterIP
  selector:
    {{- include "blastr.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: web
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
